//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroAlumnos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistroEntities1 : DbContext
    {
        public RegistroEntities1()
            : base("name=RegistroEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<grd_grado> grd_grado { get; set; }
        public virtual DbSet<mat_materia> mat_materia { get; set; }
        public virtual DbSet<alm_alumno> alm_alumno { get; set; }
        public virtual DbSet<mxg_materiasxgrado> mxg_materiasxgrado { get; set; }
    }
}
